import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('real browser uploads both sets, analyzes, opens sources, saves review and downloads report', async ({ page }, testInfo) => {
  const exceptions: string[] = [];
  page.on('pageerror', (error) => exceptions.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Загрузить пример «до/после»' }).click();
  await expect(page.getByRole('button', { name: 'Запустить сравнение' })).toBeEnabled();
  await expect(page.locator('.document-list tbody tr')).toHaveCount(2);
  await expect(page.getByLabel('Все документы «до» загружены')).toBeChecked();
  await expect(page.getByLabel('Все документы «после» загружены')).toBeChecked();
  const started = page.waitForResponse((response) => response.url().endsWith('/analyze') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Запустить сравнение' }).click();
  const comparison = await (await started).json();
  expect(comparison.documents.map((doc: { side: string }) => doc.side).sort()).toEqual(['after', 'before']);
  await expect(page.getByRole('region', { name: 'Результат сравнения', exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(page.locator('.analysis-finding')).toHaveCount(3);
  for (const kind of ['potential_loss', 'duplication', 'conflict']) await expect(page.locator(`.finding-${kind}`)).toHaveCount(1);
  const card = page.locator('.finding-potential_loss');
  await card.locator('summary').click();
  const sourceResponse = page.waitForResponse((response) => response.url().includes('/sources/'));
  await card.getByRole('button', { name: /До изменений · before.docx/ }).first().click();
  const fragment = await (await sourceResponse).json();
  await expect(page.getByRole('dialog', { name: 'Источник вывода' })).toBeVisible();
  await expect(page.getByTestId('source-fragment')).not.toBeEmpty();
  expect(await page.getByTestId('source-fragment').innerText()).toBe(fragment.text);
  expect(comparison.documents.map((doc: { id: string }) => doc.id)).toContain(fragment.document_id);
  await page.getByRole('button', { name: 'Закрыть источник' }).click();
  await card.getByLabel('Комментарий эксперта').fill('Проверено по исходному пункту.');
  await card.getByRole('button', { name: 'Подтвердить', exact: true }).click();
  await expect(card.getByText('Подтверждено экспертом', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /^Функции / }).click();
  await expect(page.getByRole('region', { name: 'Изменения функций' })).toContainText('Передана');
  await expect(page.getByRole('region', { name: 'Изменения функций' })).toContainText('Запрет');
  await page.getByRole('button', { name: /^Подразделения / }).click();
  await expect(page.getByRole('region', { name: 'Изменения подразделений' })).toContainText('Переименовано');
  await page.reload();
  await page.getByRole('button', { name: 'Открыть результаты' }).click();
  await expect(page.locator('.finding-potential_loss').getByLabel('Комментарий эксперта')).toHaveValue('Проверено по исходному пункту.');
  await expect(page.locator('.finding-potential_loss')).toContainText('Подтверждено экспертом');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'JSON', exact: true }).click();
  const download = await downloadPromise;
  const report = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(report.comparison_id).toBe(comparison.id);
  expect(report.findings).toHaveLength(3);
  expect(report.reviews[0]).toMatchObject({ status: 'confirmed', comment: 'Проверено по исходному пункту.' });
  await expect(page.getByRole('button', { name: /Удалить before.docx/ })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('comparison.png'), fullPage: true });
  expect(exceptions).toEqual([]);
});

test('incomplete sets produce coverage warnings instead of an unsupported loss', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Загрузить пример «до/после»' }).click();
  await expect(page.getByRole('button', { name: 'Запустить сравнение' })).toBeEnabled();
  await page.getByLabel('Все документы «после» загружены').uncheck();
  await page.getByRole('button', { name: 'Запустить сравнение' }).click();
  await expect(page.getByRole('region', { name: 'Результат сравнения', exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(page.locator('.finding-potential_loss')).toHaveCount(0);
  await expect(page.locator('.finding-coverage_gap')).toHaveCount(1);
  await expect(page.locator('.analysis-coverage')).toContainText('После изменений: неполное покрытие');
  await page.getByRole('button', { name: 'Новое сравнение', exact: true }).click();
  await expect(page.getByText('Здесь пока чистый лист')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Запустить сравнение' })).toBeDisabled();
});

test('server documents survive reload and deletion really removes the server document', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByLabel('Выбрать документ')).toBeEnabled();
  await page.getByLabel('Выбрать документ').setInputFiles('public/examples/before.docx');
  await page.getByRole('button', { name: 'Обработать документ', exact: true }).click();
  await expect(page.getByText('Документ прочитан', { exact: true })).toBeVisible();
  const id = await page.evaluate(() => localStorage.getItem('larpsec.comparisonId'));
  await page.reload();
  await expect(page.locator('.document-list tbody tr')).toHaveCount(1);
  await page.getByRole('button', { name: /Удалить before.docx/ }).click();
  await expect(page.getByText('Здесь пока чистый лист')).toBeVisible();
  const response = await page.request.get(`/api/v1/comparisons/${id}`);
  expect((await response.json()).documents).toEqual([]);
});
